# Generated by Django 4.2.1 on 2023-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name_one_team',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='name_two_team',
            field=models.CharField(default='', max_length=50),
        ),
    ]
