# Generated by Django 4.2.1 on 2023-05-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_new_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='sub_title',
            field=models.TextField(default='', max_length=200),
        ),
    ]
