# Generated by Django 4.2.1 on 2023-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_new_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='instance',
            field=models.CharField(default='', max_length=50),
        ),
    ]
