# Generated by Django 4.2.1 on 2023-05-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_match_date_alter_match_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match", name="date", field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="match", name="time", field=models.TimeField(auto_now=True),
        ),
    ]
