# Generated by Django 4.2.1 on 2023-05-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_match_date_alter_match_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
