# Generated by Django 4.2.1 on 2023-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_match_date_alter_match_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLigaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_team', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=50)),
                ('ganados', models.IntegerField()),
                ('empatados', models.IntegerField()),
                ('perdidos', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_encontra', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('puntos', models.IntegerField()),
            ],
        ),
    ]
