# Generated by Django 4.2.1 on 2023-06-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_positionligaprofesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionligaprofesional',
            name='jugados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
