# Generated by Django 4.2.1 on 2023-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_positionligaprofesional_jugados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='new',
            name='other_description',
            field=models.TextField(max_length=500),
        ),
    ]
