# Generated by Django 4.2.1 on 2023-06-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_new_description_alter_new_other_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='other_description',
            field=models.TextField(),
        ),
    ]
